[package]
name = "hopalong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.27.0"
image = "0.25.2"
rayon = "1.10.0"
